### ISSUE TITLE
Bash and Linux Tutorial

### ISSUE THREAD

**Issue by dileep-kishore** [BRITE-REU/programming-workshops#1]
# Outline
- [x] Main Intro @dileep-kishore
- [x] CLI Intro @JeffreyMaurer @aa2788 
- [x] Navigation @JeffreyMaurer @aa2788 
- [x] File operations @JeffreyMaurer
- [x] Grep/Awk/Sed @aa2788 
- [x] Piping and Redirection @dileep-kishore
- [x] nano/vim (file editing in the terminal) @JeffreyMaurer 
- [x] Processes @dileep-kishore
- [x] Bash scripting @dileep-kishore
- [x] Tips and tricks

# TODO:

## Before they come in: (@dileep-kishore)
- [x] Ask them if they installed the terminal?
- [x] Ask them to watch videos and read the material
- [x] Text files (Mary had a little lamb)

## In class:
1. recap (30min) @dileep-kishore
2. Grep/awk/sed (20min) @aa2788
3. vim (10min) @dileep-kishore
4. terminal quest @dileep-kishore @aa2788 
5. bash scripting (20min) @dileep-kishore

**Comment by dileep-kishore** [comment]
@JeffreyMaurer make sure you talk about permissions in the section on file operations

**Comment by JeffreyMaurer** [comment]
Gotcha, I shall!

Jeff

________________________________
